alter table public.files enable row level security;
drop policy if exists "Users can view own files" on public.files;
create policy "Users can view own files" on public.files for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Users can insert own files" on public.files;
create policy "Users can insert own files" on public.files for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users can update own files" on public.files;
create policy "Users can update own files" on public.files for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can delete own files" on public.files;
create policy "Users can delete own files" on public.files for delete to authenticated using (auth.uid() = user_id);
create index if not exists files_user_id_created_at_idx on public.files (user_id, created_at desc);
